openapi: 3.0.1
info:
  title: Product Search API
  version: 1.0.0
  description: API pour rechercher des produits

paths:
  /products:
    get:
      summary: Recherche de produits
      description: Retourne une liste de produits filtrés par terme de recherche et limités par un nombre maximum.
      parameters:   # query parameters définis dans un components en dessous
        - $ref: '#/components/parameters/limit'
        - $ref: '#/components/parameters/q'
      responses:
        '200':
          description: Liste des produits trouvés
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
              examples:
                multipleProducts:
                  summary: Plusieurs produits trouvés
                  value:
                    - name: "Yaourt nature"
                      expiration_datetime: "2025-09-30T23:59:59Z"
                      price: 1.50
                    - name: "Pain complet"
                      expiration_datetime: "2025-09-01T10:00:00Z"
                      price: 2.10
                emptyList:
                  summary: Aucun produit trouvé
                  value: []

components:
  parameters:
    limit:
      name: limit
      in: query
      description: Nombre maximum d’éléments à retourner
      required: false
      schema:
        type: integer
        example: 5
    q:
      name: q
      in: query
      description: Terme de recherche pour filtrer les produits
      required: false
      schema:
        type: string
        example: "yaourt"

  schemas:
    Product:
      type: object
      required:
        - name
        - expiration_datetime
        - price
      properties:
        name:
          type: string
          example: "Yaourt nature"
        expiration_datetime:
          type: string
          format: date-time
          example: "2025-09-30T23:59:59Z"
        price:
          type: number
          format: float
          example: 1.50